export interface Meeting {
  id: string;
  title: string;
  department: string;
  participants: string;
  date: string;
  content: string;
  summary: string; // Markdown summary generated by AI
  actionItems: string[]; // Key action items from AI
  isAiSummarized: boolean;
  createdAt: string;
}

export type RecordingStatus = 'idle' | 'listening' | 'paused' | 'error';
